name: "Bump app package version"
description: "A GitHub action to bump your package.json version"
author: "Mathieu Acthernoene"

# https://haya14busa.github.io/github-action-brandings
branding:
  icon: "arrow-up"
  color: "blue"

inputs:
  type:
    description: "The release type (must be `patch`, `minor` or `major`)"
    required: true
  prefix:
    description: "The release name prefix (could be `v`)"
    required: false
    default: ""

outputs:
  old_version:
    description: "The old package version"
  new_version:
    description: "The new package version"

runs:
  using: node20
  main: dist/index.js
